### ISSUE TITLE
tagging "Open" as NNP

### ISSUE THREAD

**Issue by dcbartlett** [dariusk/pos-js#12]
When i pass in a string to the Tagger().tag() it is returning Open as "NNP".  The below gist has the exact code used to produce this.

GIST:
https://gist.github.com/dcbartlett/221200796a239b8cfca7

This may be an issue that needs to be aimed at [jspos](https://code.google.com/p/jspos)

**Comment by dariusk** [comment]
Thanks. I fixed it locally and pushed to npm.

**Comment by MichaelPaulukonis** [comment]
Is this an incorrect classification?

"I didn't participate in the Open this year -- I had burned my clubs in a rage."

**Comment by dariusk** [comment]
Fair, it seems correct for title-cased "Open" -- I'll revert it.

**Comment by dariusk** [comment]
@MichaelPaulukonis fixed it in 0ef27ee61bc7af5bc6e72512da1c404094fea9cd

**Comment by MichaelPaulukonis** [comment]
Perhaps a more complicated rubric is required - Capital-O Open at the beginning of a sentence would seldom be the NNP (since NNP-Open should be preceded by... something else).

**Comment by dariusk** [comment]
I believe the intent of this project, in providing a list of possible tags rather than a definitive tag, is for the user to supply extra rubrics as needed. (I'm just the maintainer, not the creator, so I'm open to changing this if necessary.)

**Comment by MichaelPaulukonis** [comment]
Yep, I understand.

Is there an easy way, without changing code, to add rules, or over-ride the lexicon?

I'm not seeing it in a quick look.

Something for me to poke with a long-stick....

(That's why I like EsLint -- you can turn things on and off, and extend it, without changing the code. As far as linters go, that is. Not lexers.)

**Comment by dariusk** [comment]
You'd have to create a wrapper of some kind, I think. All the
transformational rules are here:

https://github.com/dariusk/pos-js/blob/master/POSTagger.js#L66-L118

I bet it wouldn't be too hard to provide a way to turn those into an array
of functions and then expose the array via a getter/setter?

**Comment by Hugo-ter-Doest** [comment]
The problem here is that the transformational rules are hard-coded. Originally, this was not intended by Eric Brill. I implemented a version of the Brill tagger that has transformational rules specified externally in a file. Such rules look like this:
VBD NN PREV-TAG DT
VBP NN PREV-TAG DT
VB NN PREV-TAG DT
NN CD CURRENT-WORD-IS-NUMBER YES
NNP CD CURRENT-WORD-IS-NUMBER YES
NNS CD CURRENT-WORD-IS-NUMBER YES

The module is here:
https://github.com/Hugo-ter-Doest/brill-pos-tagger

In the folder input_material you find some papers by Brill that give examples of rules and explain how these were extracted.

Regards,
Hugo

**Comment by dariusk** [comment]
That seems like it would require a whole other lexer to interpret those rules. I feel like exposing the hard-coded transformational rules and making them rewriteable but in plain JS might be the way to go here.

**Comment by Hugo-ter-Doest** [comment]
Just some thoughts. You could define the transformation rules as separate functions (in an array or object) and then apply these rules one after the other. The main clause in my tagger looks like this:
  
// Apply transformation rules
  for (var i = 0; i < sentence.length; i++) {
    this.transformation_rules.forEach(function(rule) {
      rule.apply(tagged_sentence, i);
    });
  }

Hugo

**Comment by Hugo-ter-Doest** [comment]
I converted the tranformation rules to separate functions and added getters and setters to add or replace rules. See 

https://gist.github.com/Hugo-ter-Doest/cb76b59a95ba2eb1ad27

Is this what you mean? 

Then I could go on and integrate and test this code.

Hugo

**Comment by MichaelPaulukonis** [comment]
That looks like what I was vaguely thinking of.
